# Generated by Django 5.1.5 on 2025-02-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Категория номи')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Фон расм')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Тавсиф')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Яратилган сана')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категориялар',
                'ordering': ['name'],
            },
        ),
    ]
