# Generated by Django 5.1.5 on 2025-02-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='work_time',
            field=models.TimeField(null=True),
        ),
    ]
