# Generated by Django 5.1.6 on 2025-02-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_work_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='serial_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
