# Generated by Django 5.1.6 on 2025-02-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_attendance_serial_id_customuser_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='work_time',
            field=models.TimeField(null=True),
        ),
    ]
