# Generated by Django 5.1.5 on 2025-02-28 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'Davomat', 'verbose_name_plural': 'Davomat'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Xodim', 'verbose_name_plural': 'Xodimlar'},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Kelish vaqti'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='late_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kechikish daqiqasi'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='Sabab'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='serial_id',
            field=models.PositiveIntegerField(null=True, verbose_name='Tartib raqami'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('come', 'Kelgan'), ('absent', 'Kelmagan'), ('late', 'Kech kelgan')], default='absent', max_length=20, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL, verbose_name='Xodim'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='work_time',
            field=models.TimeField(null=True, verbose_name='Ish vaqti'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana"),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Xodim ID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Familiya'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lavozim'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='work_time',
            field=models.TimeField(null=True, verbose_name='Ish vaqti'),
        ),
        migrations.CreateModel(
            name='AttendanceItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marked_at', models.DateTimeField(verbose_name='Sana')),
                ('serial_id', models.PositiveIntegerField(null=True, verbose_name='Tartib raqami')),
                ('status', models.CharField(choices=[('came', 'Keldi'), ('left', 'Ketdi')], default='left', max_length=20, verbose_name='Holat')),
                ('data', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances_items', to=settings.AUTH_USER_MODEL, verbose_name='Xodim')),
            ],
            options={
                'verbose_name': 'Davomat',
                'verbose_name_plural': 'Davomat',
            },
        ),
    ]
