# Generated by Django 5.1.5 on 2025-02-28 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_attendance_options_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceitems',
            name='attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances_items', to='users.attendance', verbose_name='Davomat'),
        ),
    ]
