# Generated by Django 5.1.5 on 2025-02-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_attendanceitems_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(unique=True, verbose_name='Ish kuni boshlanishi')),
                ('end_datetime', models.DateTimeField(verbose_name='Ish kuni tugashi')),
                ('day_type', models.CharField(choices=[('workday', 'Ish kuni'), ('weekend', 'Dam olish kuni'), ('holiday', 'Bayram kuni')], default='workday', max_length=10, verbose_name='Kun turi')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Yopiqmi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
            ],
            options={
                'verbose_name': 'Рабочий день',
                'verbose_name_plural': 'Рабочие дни',
                'ordering': ['start_datetime'],
            },
        ),
    ]
