# Generated by Django 5.1.5 on 2025-03-03 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_workingday'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='working_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='users.workingday', verbose_name='Ish kuni'),
        ),
    ]
