# Generated by Django 5.1.5 on 2025-03-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='left_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Ketish vaqti'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='work_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Ish vaqti'),
        ),
    ]
